export default [
  {
    name: 'Gilbert Awaji',
    employeeID: 1,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1890',
    age: 23,
    phoneNumber: 9083764563,
    maritalStatus: 'Single',
    email: 'successgilli@gmail.com',
    homeAddress: 'Benin Sapele Road',
    employmentType: 'Full Time',
    contractEndDate: 'nn',
    department: 'Data Science',
    salary: 100000,
    allocatedLeaveDays: 20,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 15,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Gilbert Awaji-mitop',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,

  },
  {
    name: 'Bridget Iyere',
    employeeID: 22,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1971',
    age: 37,
    phoneNumber: 9083764563,
    maritalStatus: 'Single',
    email: 'BridgetIre@gmail.com',
    homeAddress: 'upper Sakponba',
    employmentType: 'intern',
    contractEndDate: 'nn',
    department: 'Product',
    salary: 300000,
    allocatedLeaveDays: 20,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 15,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Gilbert Awaji-mitop',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,
  },
  {
    name: 'Chinedu Okeke',
    employeeID: 29,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1971',
    age: 37,
    phoneNumber: 9083764563,
    maritalStatus: 'Single',
    email: 'ChineduOkeke@gmail.com',
    homeAddress: 'upper Sakponba',
    employmentType: 'Full Time',
    contractEndDate: 'nn',
    department: 'Product',
    salary: 300000,
    allocatedLeaveDays: 25,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 20,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Chinedu Ogulogu',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,

  },
  {
    name: 'Temi Tope',
    employeeID: 12,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1971',
    age: 37,
    phoneNumber: 9083764563,
    maritalStatus: 'Maried',
    email: 'Tolutope@gmail.com',
    homeAddress: 'upper Sakponba lower',
    employmentType: 'Intern',
    contractEndDate: 'nn',
    department: 'Finance',
    salary: 300000,
    allocatedLeaveDays: 20,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 15,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Gilbert Awaji-mitop',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,
  },
  {
    name: 'Christian Obubu',
    employeeID: 28,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1971',
    age: 37,
    phoneNumber: 9083764563,
    maritalStatus: 'Single',
    email: 'ChristianeZine@gmail.com',
    homeAddress: 'Back yard',
    employmentType: 'Full Time',
    contractEndDate: 'nn',
    department: 'Data Science',
    salary: 300000,
    allocatedLeaveDays: 20,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 15,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Gilbert Awaji-mitop',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,
  },
  {
    name: 'Sofia',
    employeeID: 22,
    offerLetter: 'file Path',
    displayPicture: 'Profile pic',
    dateOfBirth: '02-Jan-1971',
    age: 37,
    phoneNumber: 9083764563,
    maritalStatus: 'Single',
    email: 'SofiDolin@gmail.com',
    homeAddress: 'Airport Road',
    employmentType: 'Full Time',
    contractEndDate: 'nn',
    department: 'Project',
    salary: 300000,
    allocatedLeaveDays: 20,
    numberofLeaveDaysTaken: 5,
    leaveBalance: 15,
    hmoLevel: 'Gold',
    staffLevel: 7,
    lastPromotionDate: '2nd of Jan 2019',
    nextOfKinName: 'Gilbert Awaji-mitop',
    nextOfKinAddress: 'Marine base P/H Rivers State',
    nextOfKinPhoneNumber: 9036746567,
    spouseName: 'Hottest',
    spouseAddress: 'Benin Road',
    spousePhoneNumber: 937938982,
    emergencyContactName: 'Emergency Name',
    emergencyContactPhoneNumber: 938798937893,
  },
];
